name: Check pipeline

on:
  pull_request:
    branches: [master]
    types: [opened, synchronize]

jobs:
  lint_and_build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: "11"
      - name: install dependencies
        run: npm install
      - name: lint
        run: npm run lint
      - name: build
        run: npm run build
